Repository UKHomeOffice/hocs-ci-infrastructure, pull requests merged in 2022-08, with the labels that each got.

#23 Introduce sql server image
  docker-compose.yml
Labels: minor

#24 👷 Add Dependabot Configuration
  .github/dependabot.yml
Labels: skip-release

#26 Reduce Gradle steps from 2 to 1 per action
  .github/workflows/codeql-analysis-jvm.yml
  .github/workflows/test-jvm.yml
Labels: patch

#27 HOCS-5438: Support multi arch builds
  .github/workflows/docker-build-branch.yml
  .github/workflows/docker-build-tag.yml
Labels: minor

#28 💚 Run apt-get update before install
  .github/workflows/test-jvm.yml
Labels: patch

#29 🐛 HOCS-5439: Replace wget healthcheck with curl
  docker-compose.yml
Labels: patch

#30 Remove now unused GitHub actions
  .github/workflows/README.md
  .github/workflows/codeql-analysis-javascript.yml
  .github/workflows/codeql-analysis-jvm.yml
  .github/workflows/docker-build-branch.yml
  .github/workflows/docker-build-tag.yml
  .github/workflows/pr-check.yml
  .github/workflows/semver-tag.yml
  .github/workflows/test-javascript.yml
  .github/workflows/test-jvm.yml
  README.md
Labels: skip-release
